_RAINBOW_M4 = 1
_RAINBOW_CLASSIC = 1

ifndef IMPLEMENTAITON_PATH
	ifdef _RAINBOW_REF
	CPPFLAGS += -D_RAINBOW_REF=$(_RAINBOW_REF)
		ifdef _RAINBOW_COMPRESSED
			IMPLEMENTATION_PATH = rainbowm4/crypto_sign/rainbowI-compressed/ref
			CPPFLAGS += -D_RAINBOW_COMPRESSED=$(_RAINBOW_COMPRESSED)
		else ifdef _RAINBOW_CLASSIC
			IMPLEMENTATION_PATH = rainbowm4/crypto_sign/rainbowI-classic/ref
			CPPFLAGS += -D_RAINBOW_CLASSIC=$(_RAINBOW_CLASSIC)
		endif
	else ifdef _RAINBOW_M4
	CPPFLAGS += -D_RAINBOW_M4=$(_RAINBOW_M4)
		ifdef _RAINBOW_COMPRESSED
			IMPLEMENTATION_PATH = rainbowm4/crypto_sign/rainbowI-compressed/m4
			CPPFLAGS += -D_RAINBOW_REF=$(_RAINBOW_REF)
		else ifdef _RAINBOW_CLASSIC
			IMPLEMENTATION_PATH = rainbowm4/crypto_sign/rainbowI-classic/m4
			CPPFLAGS +=  -D_RAINBOW_CLASSIC=$(_RAINBOW_CLASSIC)
		endif
	else
	$(error IMPLEMENTATION_PATH not set)
	endif
endif


CFLAGS += -g
CPPFLAGS += -DMUPQ_NAMESPACE=$(MUPQ_NAMESPACE) -DPRECOMPUTE_BITSLICING=0 -DUSE_HARDWARE_CRYPTO=0

COMMONS_DIR = rainbowm4/common

INCLUDES += -I$(IMPLEMENTATION_PATH) -I$(COMMONS_DIR)

COMMONSOURCES=$(COMMONS_DIR)/fips202.c $(COMMONS_DIR)/sp800-185.c $(COMMONS_DIR)/nistseedexpander.c

COMMONSOURCES_HOST=$(COMMONSOURCES) $(COMMONS_DIR)/keccakf1600.c $(COMMONS_DIR)/aes-ref.c  $(COMMONS_DIR)/sha2-ref.c  $(COMMONS_DIR)/sha2.c

COMMONSOURCES_M4=$(COMMONSOURCES) $(COMMONS_DIR)/keccakf1600.S $(COMMONS_DIR)/aes.c $(COMMONS_DIR)/aes-encrypt.S $(COMMONS_DIR)/aes-keyschedule.S $(COMMONS_DIR)/sha2.c $(COMMONS_DIR)/crypto_hashblocks_sha512.c $(COMMONS_DIR)/crypto_hashblocks_sha512_inner32.s


VICTIM_CFILES += main.c
# VICTIM_CFILES += $(IMPLEMENTATION_SOURCES)

VICTIM_AFILES += $(filter %.S,$(COMMONSOURCES_M4))

VICTIM_CFILES += $(filter %.c,$(COMMONSOURCES_M4))

VICTIM_CFILES += $(wildcard $(IMPLEMENTATION_PATH)/*.c)
VICTIM_AFILES += $(wildcard $(IMPLEMENTATION_PATH)/*.s) 
VICTIM_AFILES += $(wildcard $(IMPLEMENTATION_PATH)/*.S)

.PHONY: all
all:
	$(info IMPLEMENTATION_PATH: $(IMPLEMENTATION_PATH))
	$(info VICTIM_AFILES: $(VICTIM_AFILES))
	$(info VICTIM_CFILES: $(VICTIM_CFILES))